// apps/angular-lab/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { ProductTableComponent } from './components/product-table.component';
import { StoreCounterComponent } from './components/store-counter.component';
import { TypeaheadComponent } from './components/typeahead.component';
import { VirtualListComponent } from './components/virtual-list.component';

type TabKey = 'typeahead' | 'table' | 'virtual' | 'store';

@Component({
  selector: 'app-root',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TypeaheadComponent, ProductTableComponent, VirtualListComponent, StoreCounterComponent],
  template: `
    <main>
      <header>
        <h1>Angular Lab</h1>
        <p class="muted">
          Every demo here has a React twin in <code>apps/react-lab</code>.
        </p>
      </header>

      <nav class="tabs" role="tablist">
        @for (item of tabs; track item.key) {
          <button
            type="button"
            role="tab"
            [attr.aria-selected]="tab() === item.key"
            [class]="tab() === item.key ? 'tab active' : 'tab'"
            (click)="tab.set(item.key)"
          >
            {{ item.label }}
          </button>
        }
      </nav>

      <!-- @switch/@if/@for: the built-in control flow that replaced *ngIf and
           *ngFor in v17. It is compiled, not a directive, so it needs no import
           and produces smaller, faster output. -->
      @switch (tab()) {
        @case ('typeahead') { <app-typeahead /> }
        @case ('table') { <app-product-table /> }
        @case ('virtual') { <app-virtual-list /> }
        @case ('store') { <app-store-counter /> }
      }
    </main>
  `,
})
export class AppComponent {
  protected readonly tab = signal<TabKey>('typeahead');
  protected readonly tabs: readonly { key: TabKey; label: string }[] = [
    { key: 'typeahead', label: 'Typeahead' },
    { key: 'table', label: 'Table' },
    { key: 'virtual', label: 'Virtual list' },
    { key: 'store', label: 'Store' },
  ];
}

// apps/react-lab/src/App.tsx
import { useState } from 'react';
import { ErrorBoundary } from './components/ErrorBoundary.js';
import { ProductTable } from './components/ProductTable.js';
import { StoreCounter } from './components/StoreCounter.js';
import { Typeahead } from './components/Typeahead.js';
import { VirtualList } from './components/VirtualList.js';

const TABS = {
  typeahead: { label: 'Typeahead', render: () => <Typeahead /> },
  table: { label: 'Table', render: () => <ProductTable /> },
  virtual: { label: 'Virtual list', render: () => <VirtualList /> },
  store: { label: 'Store', render: () => <StoreCounter /> },
} as const;

type TabKey = keyof typeof TABS;

export function App(): React.JSX.Element {
  const [tab, setTab] = useState<TabKey>('typeahead');

  return (
    <main>
      <header>
        <h1>React Lab</h1>
        <p className="muted">
          Each demo has an Angular twin in <code>apps/angular-lab</code>. Read both, then read{' '}
          <code>docs/03-angular/react-vs-angular.md</code>.
        </p>
      </header>

      <nav className="tabs" role="tablist">
        {(Object.keys(TABS) as TabKey[]).map((key) => (
          <button
            key={key}
            type="button"
            role="tab"
            aria-selected={tab === key}
            className={tab === key ? 'tab active' : 'tab'}
            onClick={() => setTab(key)}
          >
            {TABS[key].label}
          </button>
        ))}
      </nav>

      <ErrorBoundary>{TABS[tab].render()}</ErrorBoundary>
    </main>
  );
}
