// apps/react-lab/src/components/VirtualList.tsx
import { PRODUCTS, formatPrice } from '@lab/core';
import { useEffect, useMemo, useRef, useState } from 'react';

/**
 * Fixed-height windowing in ~30 lines.
 *
 * The interview question behind it: "we render 50,000 rows and scrolling
 * janks — what do you do?" Answer: stop rendering what nobody can see. Keep a
 * spacer of `total * rowHeight` so the scrollbar stays honest, translate the
 * visible slice, and add an overscan buffer so fast scrolls do not flash blank.
 *
 * Say the limits too: fixed row height is the easy case; variable heights need
 * measurement + a position cache (that is what TanStack Virtual does), and
 * `content-visibility: auto` covers some cases with no JS at all.
 */
const ROW_HEIGHT = 32;
const OVERSCAN = 6;

export function VirtualList(): React.JSX.Element {
  const items = useMemo(
    () => Array.from({ length: 50_000 }, (_, i) => PRODUCTS[i % PRODUCTS.length]!),
    [],
  );
  const viewportRef = useRef<HTMLDivElement>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [viewportHeight, setViewportHeight] = useState(320);

  // Measure instead of hard-coding: the window must survive a resized container.
  useEffect(() => {
    const element = viewportRef.current;
    if (!element || typeof ResizeObserver === 'undefined') return;
    const observer = new ResizeObserver(([entry]) => {
      if (entry) setViewportHeight(entry.contentRect.height);
    });
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  const first = Math.max(0, Math.floor(scrollTop / ROW_HEIGHT) - OVERSCAN);
  const visibleCount = Math.ceil(viewportHeight / ROW_HEIGHT) + OVERSCAN * 2;
  const slice = items.slice(first, first + visibleCount);

  return (
    <section className="card">
      <h2>Virtual list — 50,000 rows, ~20 DOM nodes</h2>
      <div
        ref={viewportRef}
        className="viewport"
        onScroll={(event) => setScrollTop(event.currentTarget.scrollTop)}
      >
        <div style={{ height: items.length * ROW_HEIGHT, position: 'relative' }}>
          <ul
            style={{
              transform: `translateY(${first * ROW_HEIGHT}px)`,
              position: 'absolute',
              inset: 0,
              margin: 0,
              padding: 0,
              listStyle: 'none',
            }}
          >
            {slice.map((product, index) => (
              <li key={first + index} style={{ height: ROW_HEIGHT }}>
                <span className="muted">#{first + index}</span> {product.name}
                <span className="muted"> · {formatPrice(product.priceCents)}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
      <p className="hint">
        Rendered rows: {slice.length} of {items.length.toLocaleString()}
      </p>
    </section>
  );
}

// apps/angular-lab/src/app/components/virtual-list.component.ts
import { PRODUCTS, formatPrice, type Product } from '@lab/core';
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';

/**
 * The Angular twin of `VirtualList.tsx`. Identical maths, different reactivity.
 *
 * In production you would reach for `@angular/cdk/scrolling`
 * (`<cdk-virtual-scroll-viewport>`), which is the answer the interviewer wants
 * to hear — but being able to write the 30-line version is what proves you know
 * what the CDK is doing.
 */
const ROW_HEIGHT = 32;
const OVERSCAN = 6;
const VIEWPORT_HEIGHT = 320;

@Component({
  selector: 'app-virtual-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="card">
      <h2>Virtual list — 50,000 rows, ~20 DOM nodes</h2>
      <div class="viewport" (scroll)="onScroll($event)">
        <div [style.height.px]="items.length * rowHeight" style="position:relative">
          <ul
            [style.transform]="'translateY(' + first() * rowHeight + 'px)'"
            style="position:absolute; inset:0; margin:0; padding:0; list-style:none"
          >
            @for (product of slice(); track $index) {
              <li [style.height.px]="rowHeight">
                <span class="muted">#{{ first() + $index }}</span> {{ product.name }}
                <span class="muted"> · {{ price(product.priceCents) }}</span>
              </li>
            }
          </ul>
        </div>
      </div>
      <p class="hint">Rendered rows: {{ slice().length }} of {{ items.length }}</p>
    </section>
  `,
})
export class VirtualListComponent {
  protected readonly rowHeight = ROW_HEIGHT;
  protected readonly items: readonly Product[] = Array.from(
    { length: 50_000 },
    (_, index) => PRODUCTS[index % PRODUCTS.length] as Product,
  );

  private readonly scrollTop = signal(0);

  protected readonly first = computed(() =>
    Math.max(0, Math.floor(this.scrollTop() / ROW_HEIGHT) - OVERSCAN),
  );

  protected readonly slice = computed(() => {
    const count = Math.ceil(VIEWPORT_HEIGHT / ROW_HEIGHT) + OVERSCAN * 2;
    return this.items.slice(this.first(), this.first() + count);
  });

  /**
   * Zoneless note: this handler is a template listener, so Angular schedules
   * change detection for this component after it runs. Had we attached the
   * listener manually with `addEventListener` outside the template, nothing
   * would repaint until we called `ChangeDetectorRef.markForCheck()` — that is
   * exactly the class of bug zoneless surfaces.
   */
  protected onScroll(event: Event): void {
    this.scrollTop.set((event.target as HTMLElement).scrollTop);
  }

  protected price(cents: number): string {
    return formatPrice(cents);
  }
}
