// apps/angular-lab/src/app/components/product-table.component.ts
import {
  CATEGORIES,
  PRODUCTS,
  defaultQuery,
  formatPrice,
  runQuery,
  toggleSort,
  type Product,
  type TableQuery,
} from '@lab/core';
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';

/**
 * The Angular twin of `ProductTable.tsx`, built on signals.
 *
 * Direct mapping to memorise:
 *   useState        -> signal()
 *   useMemo         -> computed()      (auto-tracked; no dependency array to get wrong)
 *   useEffect       -> effect()        (but prefer computed; effects are for I/O)
 *   useReducer      -> a signal holding the state + methods that call `update`
 *
 * The real difference: `computed` is PULL-based and lazily memoised — it does
 * not recompute until something reads it, and it tracks its dependencies at
 * runtime. React's `useMemo` is a hint, recomputed whenever the dependency
 * array changes and discarded freely. That is why "why is my useMemo running
 * again?" is a React question that has no Angular equivalent.
 */
@Component({
  selector: 'app-product-table',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="card">
      <h2>Product table — signals + computed</h2>

      <div class="toolbar">
        <input
          class="input"
          aria-label="Filter by name"
          placeholder="Filter by name…"
          [value]="query().search"
          (input)="setSearch($any($event.target).value)"
        />
        <select aria-label="Category" [value]="query().category" (change)="setCategory($any($event.target).value)">
          <option value="all">All categories</option>
          @for (category of categories; track category) {
            <option [value]="category">{{ category }}</option>
          }
        </select>
        <label class="checkbox">
          <input type="checkbox" [checked]="query().inStockOnly" (change)="setInStockOnly($any($event.target).checked)" />
          In stock only
        </label>
      </div>

      <table>
        <thead>
          <tr>
            @for (column of columns; track column.key) {
              <th [attr.aria-sort]="ariaSort(column.key)">
                <button type="button" (click)="sortBy(column.key)">
                  {{ column.label }}{{ indicator(column.key) }}
                </button>
              </th>
            }
          </tr>
        </thead>
        <tbody>
          <!-- track is mandatory in @for. It is the equivalent of React's key
               prop, and Angular enforces it at compile time - one of the few
               places Angular is stricter than React by default. -->
          @for (product of result().rows; track product.id) {
            <tr>
              <td>{{ product.name }}</td>
              <td class="muted">{{ product.category }}</td>
              <td>{{ price(product.priceCents) }}</td>
              <td>{{ product.rating.toFixed(1) }}</td>
              <td>{{ product.inStock ? 'Yes' : 'No' }}</td>
            </tr>
          } @empty {
            <tr><td class="muted" [attr.colspan]="columns.length">No products match this filter.</td></tr>
          }
        </tbody>
      </table>

      <div class="toolbar">
        <button type="button" [disabled]="result().page <= 1" (click)="setPage(result().page - 1)">Previous</button>
        <span class="muted">Page {{ result().page }} of {{ result().pageCount }} · {{ result().total }} rows</span>
        <button type="button" [disabled]="result().page >= result().pageCount" (click)="setPage(result().page + 1)">Next</button>
      </div>
    </section>
  `,
})
export class ProductTableComponent {
  protected readonly categories = CATEGORIES;
  protected readonly columns: readonly { key: keyof Product; label: string }[] = [
    { key: 'name', label: 'Name' },
    { key: 'category', label: 'Category' },
    { key: 'priceCents', label: 'Price' },
    { key: 'rating', label: 'Rating' },
    { key: 'inStock', label: 'Stock' },
  ];

  protected readonly query = signal<TableQuery>(defaultQuery);

  /** Recomputed only when `query` actually changes, and only when read. */
  protected readonly result = computed(() => runQuery(PRODUCTS, this.query()));

  // Every filter mutation resets the page — same invariant as the React reducer.
  protected setSearch(search: string): void {
    this.query.update((q) => ({ ...q, search, page: 1 }));
  }
  protected setCategory(category: TableQuery['category']): void {
    this.query.update((q) => ({ ...q, category, page: 1 }));
  }
  protected setInStockOnly(inStockOnly: boolean): void {
    this.query.update((q) => ({ ...q, inStockOnly, page: 1 }));
  }
  protected sortBy(key: keyof Product): void {
    this.query.update((q) => ({ ...q, sort: toggleSort(q.sort, key), page: 1 }));
  }
  protected setPage(page: number): void {
    this.query.update((q) => ({ ...q, page }));
  }

  protected ariaSort(key: keyof Product): 'ascending' | 'descending' | 'none' {
    const sort = this.query().sort;
    if (sort.key !== key) return 'none';
    return sort.direction === 'asc' ? 'ascending' : 'descending';
  }
  protected indicator(key: keyof Product): string {
    const sort = this.query().sort;
    if (sort.key !== key) return '';
    return sort.direction === 'asc' ? ' ▲' : ' ▼';
  }
  protected price(cents: number): string {
    return formatPrice(cents);
  }
}

// apps/react-lab/src/components/ProductTable.tsx
import {
  CATEGORIES,
  PRODUCTS,
  defaultQuery,
  formatPrice,
  runQuery,
  toggleSort,
  type Product,
  type TableQuery,
} from '@lab/core';
import { useMemo, useReducer } from 'react';

/**
 * Sortable / filterable / paginated table.
 *
 * Two senior-level points to make while writing this:
 *
 * 1. `useReducer` over five `useState`s. The state fields are coupled — changing
 *    the filter must reset the page to 1 — and a reducer makes that invariant a
 *    single line instead of a rule everyone has to remember at every call site.
 *
 * 2. `useMemo` here is real, not cargo cult. `runQuery` sorts the whole dataset;
 *    without the memo it re-sorts on every keystroke in an unrelated input.
 *    Rule of thumb: memoize O(n log n) work, not `a + b`. With the React
 *    Compiler enabled you would drop the manual memo and let it insert one.
 */
type Action =
  | { type: 'search'; value: string }
  | { type: 'category'; value: TableQuery['category'] }
  | { type: 'inStockOnly'; value: boolean }
  | { type: 'sort'; key: keyof Product }
  | { type: 'page'; value: number };

function reducer(state: TableQuery, action: Action): TableQuery {
  switch (action.type) {
    // Every filter change resets pagination — the invariant lives here, once.
    case 'search':
      return { ...state, search: action.value, page: 1 };
    case 'category':
      return { ...state, category: action.value, page: 1 };
    case 'inStockOnly':
      return { ...state, inStockOnly: action.value, page: 1 };
    case 'sort':
      return { ...state, sort: toggleSort(state.sort, action.key), page: 1 };
    case 'page':
      return { ...state, page: action.value };
  }
}

const COLUMNS: readonly { key: keyof Product; label: string }[] = [
  { key: 'name', label: 'Name' },
  { key: 'category', label: 'Category' },
  { key: 'priceCents', label: 'Price' },
  { key: 'rating', label: 'Rating' },
  { key: 'inStock', label: 'Stock' },
];

export function ProductTable(): React.JSX.Element {
  const [query, dispatch] = useReducer(reducer, defaultQuery);
  const result = useMemo(() => runQuery(PRODUCTS, query), [query]);

  return (
    <section className="card">
      <h2>Product table — useReducer + derived state</h2>

      <div className="toolbar">
        <input
          className="input"
          aria-label="Filter by name"
          placeholder="Filter by name…"
          value={query.search}
          onChange={(event) => dispatch({ type: 'search', value: event.target.value })}
        />
        <select
          aria-label="Category"
          value={query.category}
          onChange={(event) =>
            dispatch({ type: 'category', value: event.target.value as TableQuery['category'] })
          }
        >
          <option value="all">All categories</option>
          {CATEGORIES.map((category) => (
            <option key={category} value={category}>
              {category}
            </option>
          ))}
        </select>
        <label className="checkbox">
          <input
            type="checkbox"
            checked={query.inStockOnly}
            onChange={(event) => dispatch({ type: 'inStockOnly', value: event.target.checked })}
          />
          In stock only
        </label>
      </div>

      <table>
        <thead>
          <tr>
            {COLUMNS.map((column) => {
              const active = query.sort.key === column.key;
              return (
                <th
                  key={String(column.key)}
                  aria-sort={active ? (query.sort.direction === 'asc' ? 'ascending' : 'descending') : 'none'}
                >
                  <button type="button" onClick={() => dispatch({ type: 'sort', key: column.key })}>
                    {column.label}
                    {active ? (query.sort.direction === 'asc' ? ' ▲' : ' ▼') : ''}
                  </button>
                </th>
              );
            })}
          </tr>
        </thead>
        <tbody>
          {result.rows.map((product) => (
            <tr key={product.id}>
              <td>{product.name}</td>
              <td className="muted">{product.category}</td>
              <td>{formatPrice(product.priceCents)}</td>
              <td>{product.rating.toFixed(1)}</td>
              <td>{product.inStock ? 'Yes' : 'No'}</td>
            </tr>
          ))}
          {result.rows.length === 0 && (
            <tr>
              <td colSpan={COLUMNS.length} className="muted">
                No products match this filter.
              </td>
            </tr>
          )}
        </tbody>
      </table>

      <div className="toolbar">
        <button
          type="button"
          disabled={result.page <= 1}
          onClick={() => dispatch({ type: 'page', value: result.page - 1 })}
        >
          Previous
        </button>
        <span className="muted">
          Page {result.page} of {result.pageCount} · {result.total} rows
        </span>
        <button
          type="button"
          disabled={result.page >= result.pageCount}
          onClick={() => dispatch({ type: 'page', value: result.page + 1 })}
        >
          Next
        </button>
      </div>
    </section>
  );
}
